=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/schema/OfficeEMR_B10_Schema_v1-OCT2023/consent.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "array",
  "items": {
    "description": "",
    "type": "object",
    "properties": {
      "patientid": {
        "description": "",
        "type": "number"
      },
      "phoneConsent": {
        "description": "",
        "type": "string"
      },
      "phoneType": {
        "description": "",
        "type": "string"
      },
      "phone": {
        "description": "",
        "type": "string"
      },
      "textConsent": {
        "description": "",
        "type": "string"
      },
      "textType": {
        "description": "",
        "type": "string"
      },
      "text": {
        "description": "",
        "type": "string"
      },
      "emailConsent": {
        "description": "",
        "type": "string"
      },
      "emailType": {
        "description": "",
        "type": "string"
      },
      "email": {
        "description": "",
        "type": "string"
      },
      "prescriptionEducationTextConsent": {
        "description": "",
        "type": "string"
      },
      "hieConsent": {
        "description": "",
        "type": "string"
      },
      "hieConsentDate": {
        "description": "",
        "type": "string"
      }
    }
  }
}

=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/sample-export/consent.json
[
  {
    "patientid": 311322,
    "phoneConsent": "Y",
    "phoneType": "Work",
    "phone": "(847) 275-6951",
    "textConsent": "N",
    "textType": "Home",
    "text": "(317) 449-0408",
    "emailConsent": "N",
    "emailType": "Override",
    "email": "test@test.com",
    "prescriptionEducationTextConsent": "Y",
    "hieConsent": "Granted",
    "hieConsentDate": "20230901"
  }
]
