=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/schema/OfficeEMR_B10_Schema_v1-OCT2023/epa.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "array",
  "items": {
    "description": "",
    "type": "object",
    "properties": {
      "prescriptionId": {
        "description": "Unique identifier for the prescription",
        "type": "number"
      },
      "patientId": {
       "description": "",
        "type": "number"
      },
      "epaTaskStatus": {
       "description": "",
        "type": ["string", "null"]
      },
      "postDateUtc": {
       "description": "",
        "type": ["string", "null"]
      }
    },
    "required": ["prescriptionId", "patientId"]
  }
}

=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/sample-export/epa.json
[
  {
    "prescriptionId": 8647,
    "patientId": 311322,
    "epaTaskStatus": "Open",
    "postDateUtc": "20230918124755-0400"
  },
  {
    "prescriptionId": 8660,
    "patientId": 311322,
    "epaTaskStatus": "Approved",
    "postDateUtc": "20230919115030-0400"
  },
  {
    "prescriptionId": 8664,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230928142107-0400"
  },
  {
    "prescriptionId": 8665,
    "patientId": 311322,
    "epaTaskStatus": "Open",
    "postDateUtc": "20231012150841-0400"
  },
  {
    "prescriptionId": 8666,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20231004135230-0400"
  },
  {
    "prescriptionId": 8667,
    "patientId": 311322,
    "epaTaskStatus": "Denied",
    "postDateUtc": "20231004155123-0400"
  },
  {
    "prescriptionId": 8668,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230920124737-0400"
  },
  {
    "prescriptionId": 8671,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230921112851-0400"
  },
  {
    "prescriptionId": 8672,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230920125507-0400"
  },
  {
    "prescriptionId": 8674,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230921112738-0400"
  },
  {
    "prescriptionId": 8675,
    "patientId": 311322,
    "epaTaskStatus": "Cancelled",
    "postDateUtc": "20230920130158-0400"
  },
  {
    "prescriptionId": 8676,
    "patientId": 311322,
    "epaTaskStatus": "Approved",
    "postDateUtc": "20230921112015-0400"
  },
  {
    "prescriptionId": 8678,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230928102049-0400"
  },
  {
    "prescriptionId": 8679,
    "patientId": 311322,
    "epaTaskStatus": "Closed (Pending)",
    "postDateUtc": "20230921131908-0400"
  },
  {
    "prescriptionId": 8680,
    "patientId": 311322,
    "epaTaskStatus": "Followup",
    "postDateUtc": "20230921132149-0400"
  },
  {
    "prescriptionId": 8681,
    "patientId": 311322,
    "epaTaskStatus": "Followup",
    "postDateUtc": "20230921132350-0400"
  },
  {
    "prescriptionId": 8682,
    "patientId": 311322,
    "epaTaskStatus": "Approved (Pending)",
    "postDateUtc": "20230921132649-0400"
  },
  {
    "prescriptionId": 8683,
    "patientId": 311322,
    "epaTaskStatus": "Approved",
    "postDateUtc": "20230921132959-0400"
  },
  {
    "prescriptionId": 8685,
    "patientId": 311322,
    "epaTaskStatus": "Denied",
    "postDateUtc": "20231004155842-0400"
  }
]
