=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/schema/OfficeEMR_B10_Schema_v1-OCT2023/lab_result.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "array",
  "items": {
    "description": "",
    "type": "object",
    "properties": {
      "labResultId": {
        "description": "",
        "type": "number"
      },
      "patientId": {
         "description": "",
        "type": "number"
      },
      "orderDateUtc": {
         "description": "",
        "type": ["string", "null"]
      },
      "resultDateUtc": {
         "description": "",
        "type": ["string", "null"]
      },
      "orderResultDescription": {
       "description": "",
        "type": ["string", "null"]
      },
      "orderResultValue": {
         "description": "",
        "type": ["string", "null"]
      },
      "orderItemCode": {
         "description": "",
        "type": ["string", "null"]
      },
      "orderItemDescription": {
         "description": "",
        "type": ["string", "null"]
      },
      "loincCode": {
         "description": "",
        "type": ["string", "null"]
      },
      "loincDescription": {
         "description": "",
        "type": ["string", "null"]
      },
      "unitOfMeasure": {
         "description": "",
        "type": ["string", "null"]
      },
      "resultRange": {
        "description": "",
        "type": ["string", "null"]
      },
      "abnormalFlags": {
        "description": "",
        "type": ["string", "null"]
      },
      "labName": {
         "description": "",
        "type": ["string", "null"]
      },
      "labAddress": {
         "description": "",
        "type": ["string", "null"]
      },
      "labPhone": {
         "description": "",
        "type": ["string", "null"]
      },
      "labRequisitionId": {
         "description": "",
        "type": ["number", "null"]
      }
    },
    "required": ["labResultId", "patientId"]
  }
}

=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/sample-export/lab_result.json
[
  {
    "labResultId": 27108,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "PROTEIN, TOTAL",
    "orderResultValue": "7.8",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "2885-2",
    "loincDescription": "Prot SerPl-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "6.2-8.3",
    "abnormalFlags": "N",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27109,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "ALBUMIN",
    "orderResultValue": "5.0",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "2862-1",
    "loincDescription": "Albumin SerPl Elph-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "3.5-4.7",
    "abnormalFlags": "H",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27110,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "ALPHA-1-GLOBULINS",
    "orderResultValue": "0.5",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "2865-4",
    "loincDescription": "Alpha1 Glob SerPl Elph-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "0.1-0.3",
    "abnormalFlags": "H",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27111,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "ALPHA-2-GLOBULINS",
    "orderResultValue": "0.1",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "2868-8",
    "loincDescription": "Alpha2 Glob SerPl Elph-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "0.5-1.0",
    "abnormalFlags": "L",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27112,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "BETA GLOBULINS",
    "orderResultValue": "1.1",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "2871-2",
    "loincDescription": "B-Globulin SerPl Elph-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "0.8-1.4",
    "abnormalFlags": "N",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27113,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "GAMMA GLOBULINS",
    "orderResultValue": "13.0",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "2874-6",
    "loincDescription": "Gamma glob SerPl Elph-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "0.6-1.6",
    "abnormalFlags": "H",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27114,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "ABNORMAL PROTEIN BAND 1",
    "orderResultValue": "25",
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "51435-6",
    "loincDescription": "M Protein 1 SerPl Elph-mCnc",
    "unitOfMeasure": "g/dL",
    "resultRange": "NONE DETECTED",
    "abnormalFlags": "H",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27117,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "INTERPRETATION",
    "orderResultValue": null,
    "orderItemCode": "747SBX=",
    "orderItemDescription": "PROTEIN, TOTAL AND PROTEIN ELECTROPHORESIS",
    "loincCode": "12851-2",
    "loincDescription": "Prot PatternSerPl Elph-Imp",
    "unitOfMeasure": "",
    "resultRange": "",
    "abnormalFlags": "",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27118,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "HEPATITIS A AB, TOTAL",
    "orderResultValue": "NON-REACTIVE",
    "orderItemCode": "6462SB=",
    "orderItemDescription": "HEPATITIS PANEL",
    "loincCode": "13951-9",
    "loincDescription": "HAV Ab Ser Ql EIA",
    "unitOfMeasure": "",
    "resultRange": "NON-REACTIVE",
    "abnormalFlags": "N",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27119,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "HEPATITIS B SURFACE ANTIBODY QL",
    "orderResultValue": "BORDERLINE",
    "orderItemCode": "6462SB=",
    "orderItemDescription": "HEPATITIS PANEL",
    "loincCode": "10900-9",
    "loincDescription": "HBV surface Ab Ser Ql EIA",
    "unitOfMeasure": "",
    "resultRange": "NON-REACTIVE",
    "abnormalFlags": "A",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27120,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "HEPATITIS B SURFACE ANTIGEN",
    "orderResultValue": "NON-REACTIVE",
    "orderItemCode": "6462SB=",
    "orderItemDescription": "HEPATITIS PANEL",
    "loincCode": "5196-1",
    "loincDescription": "HBV surface Ag Ser Ql EIA",
    "unitOfMeasure": "",
    "resultRange": "NON-REACTIVE",
    "abnormalFlags": "N",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27122,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "HEPATITIS B CORE AB TOTAL",
    "orderResultValue": "REACTIVE",
    "orderItemCode": "6462SB=",
    "orderItemDescription": "HEPATITIS PANEL",
    "loincCode": "13952-7",
    "loincDescription": "HBV core Ab Ser Ql EIA",
    "unitOfMeasure": "",
    "resultRange": "NON-REACTIVE",
    "abnormalFlags": "A",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27123,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "HEPATITIS C ANTIBODY",
    "orderResultValue": "NON-REACTIVE",
    "orderItemCode": "6462SB=",
    "orderItemDescription": "HEPATITIS PANEL",
    "loincCode": "13955-0",
    "loincDescription": "HCV Ab Ser Ql EIA",
    "unitOfMeasure": "",
    "resultRange": "NON-REACTIVE",
    "abnormalFlags": "N",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27124,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "SIGNAL TO CUT-OFF",
    "orderResultValue": "1.00",
    "orderItemCode": "6462SB=",
    "orderItemDescription": "HEPATITIS PANEL",
    "loincCode": "48159-8",
    "loincDescription": "HCV Ab s/co SerPl EIA-Rto",
    "unitOfMeasure": "",
    "resultRange": "<1.00",
    "abnormalFlags": "H",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27125,
    "patientId": 311322,
    "orderDateUtc": "20120209124600-0400",
    "resultDateUtc": "20120209124600-0400",
    "orderResultDescription": "RED BLOOD CELL COUNT",
    "orderResultValue": "4.45",
    "orderItemCode": "16763SB=",
    "orderItemDescription": "HEMOGLOBINOPATHY EVALUATION (REFL)",
    "loincCode": "789-8",
    "loincDescription": "RBC # Bld Auto",
    "unitOfMeasure": "Million/uL",
    "resultRange": "4.20-5.80",
    "abnormalFlags": "N",
    "labName": "Quest Diagnostics-Dallas",
    "labAddress": "4770 Regent Blvd Irving, TX 75063-2445",
    "labPhone": "",
    "labRequisitionId": 367
  },
  {
    "labResultId": 27126,
    "patientId": 311322,
