=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/schema/OfficeEMR_B10_Schema_v1-OCT2023/phone_encounter.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "array",
  "items": {
    "description": "",
    "type": "object",
    "properties": {
      "rowIdentifier": {
        "description": "",
        "type": "number"
      },
      "patientId": {
        "description": "",
        "type": "number"
      },
      "encounterType": {
        "description": "",
        "type": "string"
      },
      "encounterId": {
        "description": "",
        "type": "number"
      },
      "memo": {
        "description": "",
        "type": "string"
      },
      "phone_number": {
        "description": "",
        "type": "string"
      },
      "talkedWithPatient": {
        "description": "",
        "type": "string"
      },
      "messageType": {
        "description": "",
        "type": "string"
      },
      "authorUserId": {
        "description": "",
        "type": "string"
      },
      "authorLogDateUtc": {
        "description": "",
        "type": "string"
      }
    }
  }
}

=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/sample-export/phone_encounter.json
[
  {
    "rowIdentifier": 129,
    "patientId": 311322,
    "encounterType": "PatientCaseManagement",
    "encounterId": 110,
    "memo": "Call completed",
    "phone_number": "(317) 449-0408",
    "talkedWithPatient": "Y",
    "messageType": "Call completed",
    "authorUserId": "!gferrer",
    "authorLogDateUtc": "20230626082656-0400"
  }
]
