=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/schema/OfficeEMR_B10_Schema_v1-OCT2023/prior_authorization_code.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "",
  "type": "array",
  "items": {
    "description": "",
    "type": "object",
    "properties": {
      "rowIdentifier": {
        "description": "",
        "type": "number"
      },
      "authorizationId": {
        "description": "",
        "type": "number"
      },
      "patientId": {
        "description": "",
        "type": "number"
      },
      "codeType": {
        "description": "",
        "type": "string"
      },
      "code": {
        "description": "",
        "type": "string"
      },
      "codeDescription": {
        "description": "",
        "type": "string"
      },
      "sortOrder": {
        "description": "",
        "type": "number"
      }
    }
  }
}

=== jmandel-bot/ehi-export-analysis/results/isalus-healthcare/downloads/sample-export/prior_authorization_code.json
[
  {
    "rowIdentifier": 1,
    "authorizationId": 63,
    "patientId": 311322,
    "codeType": "CPT",
    "code": "99203",
    "codeDescription": "NEW PATIENT OFFICE VISIT",
    "sortOrder": 2
  },
  {
    "rowIdentifier": 2,
    "authorizationId": 63,
    "patientId": 311322,
    "codeType": "CPT",
    "code": "99213",
    "codeDescription": "ESTABLISHED OFFICE VISIT Test",
    "sortOrder": 1
  },
  {
    "rowIdentifier": 3,
    "authorizationId": 63,
    "patientId": 311322,
    "codeType": "ICD10",
    "code": "R97.20",
    "codeDescription": "Elevated prostate specific antigen [PSA]",
    "sortOrder": 1
  }
]
